# Base TensorFlow image with GPU support
FROM tensorflow/tensorflow:2.13.0-gpu

# Install additional Python packages if needed
RUN pip install numpy pandas matplotlib scipy scikit-learn


# Set the working directory
WORKDIR /workspace

